name: artisan_triveni
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  intl: ^0.20.2
  open_file: ^3.5.10
  path_provider: ^2.1.5
  pdf: ^3.11.3
  photo_view: ^0.14.0
  supabase_flutter: ^2.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/